service: eat-well

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: slsUserSandbox
  region: us-east-1

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
